#!/usr/bin/perl

use Modern::Perl;

my $windowtitlefile = "$ENV{XDG_RUNTIME_DIR}/dwl-windowtitle";

my $titles = {};
my $last = '';

sub write_windowtitle {
	my ($title) = @_;

	open my $out, ">", "$windowtitlefile" or die "failed to open file: '$windowtitlefile' $!";
	print $out "$title\n";
	close $out;
}

# initialise windowtitlefile
write_windowtitle('');
chmod(0600, $windowtitlefile);

while (<>) {
	chomp;
	my ($monitor, $key, $value) = (/^\s*(\S+)\s*(\S+)\s*(.*)$/);

	for ($key) {
		/title/ && do {
			$titles->{$monitor} = $value;
			last;
		};
		/selmon/ && do {
			if ($value eq '1' and $last ne $titles->{$monitor}) {
				write_windowtitle($titles->{$monitor});
				$last = $titles->{$monitor};
			}
			last;
		};
	}
}


