#!/bin/sh

# Sure would be nice if every app supported XF86Copy, XF86Paste, and XF86Cut
# in the mean time, there's this hacky script

# use your global keybinding system to
# bind `dwl-keys copy`  to Super+C
# bind `dwl-keys paste` to Super+V
# bind `dwl-keys cut`   to Super+X

copy() {
	appid="$1"

	case "$appid" in
		# special cases for certain apps
		rdesktop | xfreerdp )
			xdotool sleep .2 key Escape ctrl+c
			;;

		foot )
			wtype -k XF86Copy
			;;

		# otherwise default behavior dependng on whether we have an
		# Xwayland or wayland client
		*)
			wtype -M ctrl c
			;;
	esac
}

paste() {
	appid="$1"

	case "$appid" in
		rdesktop | xfreerdp )
			xdotool sleep .2 key Escape ctrl+v
			;;

		foot )
			wtype -k XF86Paste
			;;

		*)
			wtype -M ctrl v
			;;
	esac
}

cut() {
	appid="$1"

	case "$appid" in
		rdesktop | xfreerdp )
			xdotool sleep .2 key Escape ctrl+x
			;;

		*)
			wtype -M ctrl x
			;;
	esac
}

deleteword() {
	appid="$1"

	case "$appid" in
		rdesktop | xfreerdp )
			xdotool sleep .2 key Escape key ctrl+BackSpace
			;;

		foot )
			wtype -M ctrl w
			;;

		*)
			wtype -M ctrl -k backspace
			;;
	esac
}

command="$1"
case "$command" in
	copy | paste | cut | deleteword )
		read -r appid < $XDG_RUNTIME_DIR/dwl-appid
		$command "$appid"
		;;

	*)
		echo "usage: $0 (copy|paste|cut|deleteword)"
		exit 1
		;;
esac
