#!/bin/sh

# Sure would be nice if every app supported XF86Copy, XF86Paste, and XF86Cut
# in the mean time, there's this hacky script

# use your global keybinding system to
# bind `dwl-keys copy`  to Super+C
# bind `dwl-keys paste` to Super+V
# bind `dwl-keys cut`   to Super+X

ctrl() {
	char="$1"

	read -r ctype < $XDG_RUNTIME_DIR/dwl-ctype

	# ctype 0 or 1 is wayland, 2 or 3 is xwayland
	if [ "$ctype" -ge "2" ]; then
		xdotool key ctrl+"$char"
	else
		wtype -M ctrl $char
	fi
}

copy() {
	appid="$1"

	case "$appid" in
		# special cases for certain apps
		rdesktop )
			xdotool sleep .2 key Escape ctrl+c
			;;

		Gimp )
			xdotool sleep .1 key ctrl+c
			;;

		foot )
			wtype -k XF86Copy
			;;

		# otherwise default behavior dependng on whether we have an
		# Xwayland or wayland client
		*)
			ctrl C
			;;
	esac
}

paste() {
	appid="$1"

	case "$appid" in
		rdesktop )
			xdotool sleep .2 key Escape ctrl+v
			;;

		Gimp )
			xdotool sleep .1 key ctrl+v
			;;

		foot )
			wtype -k XF86Paste
			;;

		*)
			ctrl V
			;;
	esac
}

cut() {
	appid="$1"

	case "$appid" in
		rdesktop )
			xdotool sleep .2 key Escape ctrl+x
			;;

		Gimp )
			xdotool sleep .1 key ctrl+x
			;;

		*)
			ctrl X
			;;
	esac
}

command="$1"
case "$command" in
	copy | paste | cut )
		read -r appid < $XDG_RUNTIME_DIR/dwl-appid
		$command "$appid"
		;;

	*)
		echo "usage: $0 (copy|paste|cut)"
		exit 1
		;;
esac
